### ISSUE TITLE
Can I has access please?

### ISSUE THREAD

**Issue by bmagyar** [ros2-gbp/control_msgs-release#1]
![72uG](https://user-images.githubusercontent.com/3524577/105519169-0531c480-5cd1-11eb-8d39-04a41f24e503.gif)

**Comment by nuclearsandwich** [comment]
I did a quick scan of https://github.com/ros-controls/control_msgs/commits/kinetic-devel but since I'm not an admin of that organization I can't verify that you're a maintainer there from a repository access perspective. However I do see you listed in the package.xml https://github.com/ros-controls/control_msgs/blob/kinetic-devel/control_msgs/package.xml#L10.

**Comment by nuclearsandwich** [comment]
Invitation to maintain has been dispatched. Please close the issue once you've verified you have access or let me know if you have issues.

**Comment by bmagyar** [comment]
For further reference here's my certificate of authenticity going back 6 years: https://github.com/ros/rosdistro/pulls?q=is%3Apr+is%3Aclosed+author%3Abmagyar :D

**Comment by bmagyar** [comment]
thanks: https://github.com/ros/rosdistro/pull/28064
